# Generated by Django 5.1.1 on 2024-10-18 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='MyClubSubscriber',
        ),
    ]
